# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

before:
  hooks:
    - chmod +x ./scripts/download_resources.sh
    - INSTALLER_REF=v2 ./scripts/download_resources.sh
    - sed -i 's@ORIGINAL_VERSION=.*@ORIGINAL_VERSION=v{{ .Version }}@g' 1pctl

builds:
  - id: agent
    dir: agent
    main: cmd/server/main.go
    binary: 1panel-agent
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarm:
      - 7
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x
      - riscv64
      - loong64
  - id: core
    dir: core
    main: cmd/server/main.go
    binary: 1panel-core
    flags:
      - -trimpath
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarm:
      - 7
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x
      - riscv64
      - loong64

archives:
  - formats: ['tar.gz']
    ids: [core, agent]
    name_template: "1panel-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    files:
      - 1pctl
      - install.sh
      - 1panel-core.service
      - 1panel-agent.service
      - initscript/*
      - lang/*
      - GeoIP.mmdb

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
